### PR TITLE
Automatically release nix package

### PR DESCRIPTION
**Pull request by rcambrj**
Adds configuration to `.goreleaser.yml` for a nix release.

https://goreleaser.com/customization/nix/

## to do

- [x] requires [a new repository](https://goreleaser.com/customization/nix/#setting-up-a-nur) (much like [homebrew-mach-composer](https://github.com/mach-composer/homebrew-mach-composer)):
  - [x] [create repository from template](https://github.com/new?template_name=nur-packages-template&template_owner=nix-community) `nix-mach-composer` will be consistent with the homebrew one.
  - [ ] ~give access to @goreleaserbot~
  - [x] give access to @rcambrj (pretty please)
- [x] confirm that this works and make more todos
- [x] uncomment brew + choco config

### CODE REVIEW

**Review by demeyerthom — COMMENTED** [review]
Looks good, but I think we need to re-comment the rest again :). Have you tried it with creating a beta?

**Comment by demeyerthom** [comment]
Could you also create a changie file? `changie new` and decide which type of update it is (it will determine the tag to use for next changeset). https://changie.dev/guide/installation/

**Comment by rcambrj** [comment]
@demeyerthom it's ready! you might want to consider this a major change, due to the change in behaviour when there are no config files.

**Review by demeyerthom — APPROVED** [review]
LGTM

**Pull request merged**
